import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  Maincontainer: {
    elevation: 5,
    backgroundColor: "#d3d3d3",
    width: "100%",
  },
  show: {
    display: "flex",
  },
  hide: {
    display: "none",
  },
  DropDown: {
    position: "absolute",
    top: "110%",
    display: "flex",
    backgroundColor: "#F5F5F5",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 10,
    width: "60%",
    shadowColor: "black",
    shadowOpacity: 0.35,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 5,

    // alignSelf: "center",
  },
  DropDownText: {
    // borderWidth: 1,
    // borderColor: "black",
    textAlign: "center",
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: "gray",
    borderRadius: 10,
    fontSize: 15,
    marginTop: 10,
    shadowColor: "black",
    shadowOpacity: 0.26,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 5,
  },
  container: {
    marginTop: 0,
    paddingTop: 25,
    zIndex: 10,
    padding: 10,
    backgroundColor: "#e6e6e6",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "black",
    shadowOpacity: 0.26,
    shadowOffset: { width: 5, height: 2 },
    shadowRadius: 8,
    elevation: 20,
    // position: "relative",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "Roboto",
    color: "gray",
  },
});
